#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""Expose repo-tools' Docker jobs to the project's gated release workflow.

repo-tools 0.1.30 emits a standalone Docker publisher. Preserve its jobs verbatim
and replace the event triggers with workflow_call so release.yml owns sequencing.
Registry, platforms, runners, tags, build arguments and manifest merging remain
managed by repo-tools from versions.yaml. Run through make ci/check-metadata.
"""
import argparse
from pathlib import Path

from scitrera_repo_tools.ci_gen_gha.templates import build_build_docker
from scitrera_repo_tools.version_sync.config import load_config


def render_workflow(config):
    if config.ci.docker.enable_workflow_dispatch_version:
        raise ValueError('Reusable container publication requires enable_workflow_dispatch_version: false')
    generated = build_build_docker(config, config.ci)
    _, separator, jobs = generated.partition('\njobs:\n')
    if not separator:
        raise ValueError('repo-tools did not generate Docker jobs; check docker.images')
    return '''# Generated by scripts/container_workflow.py using scitrera-repo-tools.
# Edit versions.yaml and run make ci; make check-metadata checks for drift.
# Job definitions below are emitted verbatim by repo-tools' Docker generator.
name: Publish container
on:
  workflow_call:
permissions:
  contents: read
  packages: write
jobs:
''' + jobs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    config = load_config(root / 'versions.yaml')
    desired = render_workflow(config)
    path = root / '.github/workflows/publish-container.yml'
    current = path.read_text() if path.exists() else None
    if current != desired:
        if args.check:
            parser.exit(1, 'Container workflow drift; run make ci\n')
        path.write_text(desired)
    print('Container workflow: ' + ('updated' if current != desired else 'OK'))


if __name__ == '__main__':
    main()
